# Generated by Django 3.0.4 on 2020-04-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('phonenumber', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('number_of_ratings', models.IntegerField()),
                ('profile_description', models.TextField()),
                ('picture_path', models.CharField(max_length=255, null=True)),
                ('years_experience', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myprofession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracting.Profession')),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracting.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_skills',
            field=models.ManyToManyField(through='contracting.Skills', to='contracting.Profession'),
        ),
    ]
